### ISSUE TITLE
Cannot install dependencies: No matching distribution found for fairseq==0.10.2

### ISSUE THREAD

**Issue by Bin-Huang** [microsoft/muzic#1]
Cannot install dependencies when I run  `pip install -r requirements.txt`. The major error message is as followed:

```
...
ERROR: Could not find a version that satisfies the requirement fairseq==0.10.2 (from versions: 0.6.1, 0.6.2, 0.7.1, 0.7.2, 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.10.2)
ERROR: No matching distribution found for fairseq==0.10.2
```

My development environments:
- python 3.9.7
- pip 21.2.4
- macos 11.5.2

**Comment by tan-xu** [comment]
@Bin-Huang  It is a issue related to fairseq, you can refer to this issue https://github.com/pytorch/fairseq/issues/3535 for possible solutions.

**Comment by loftwah** [comment]
This is an easy fix, you need help? I can assist.

Also, @ anyone interested from the Microsoft side of things. I think I can do things with this project that you couldn't possibly imagine.

**Comment by tanujdhiman** [comment]
Actually, This is an windows error. I tried it on Ubuntu it worked very well. But on Windows it gives me error.

**Comment by loftwah** [comment]
Is that directly on Windows or using WSL2? I highly recommend having a look at that if you haven't already and have the time.

**Comment by sevvalmehder** [comment]
I tried this issue on Ubuntu with python=3.9.7. It also gives me the same error. I assume the problem is your python version since it worked for python=3.8
