### ISSUE TITLE
[MusicBERT] Chord mappings file

### ISSUE THREAD

**Issue by FinCottle44** [microsoft/muzic#104]
Hi,

I've tried to do some research via the issues, readmes and the paper, but I can't seem to find anywhere explaining the _chord_mappings.pkl_ file within the MusicBERT repo. 

I've unpickled it and sort of understand its purpose, but wondered if there is any documentation or explanation on what it is, the data it holds and how it can be used alongside musicbert?

Any advice?

Thanks in advance

**Comment by mlzeng** [comment]
Hi @FinCottle44 ,

The mappings come from the paper PiRhDy. It's not used by MusicBERT. It's used by the script `gen_nsp.py` to convert the dataset from PiRhDy to OctupleMIDI format.
