### ISSUE TITLE
How to encode pop music？

### ISSUE THREAD

**Issue by Ramlinbird** [microsoft/muzic#11]
Nice to see the research of musicbert! And I have a question, the octupleMIDI encoding method mentioned seems only adapt to pure music. Is there any way to encode pop music with singer's voice? Thanks.

**Comment by tan-xu** [comment]
@Ramlinbird  MusicBERT and OctupleMIDI now only support symbolic music, e.g., MIDI format. For singing voice, you may need audio representation.

**Comment by tan-xu** [comment]
@Ramlinbird  You can use mel-spectrograms or MFCC or other models to represent audio. You may find them from some github projects such as ESPNet, DeepSpeech, Wav2Vec, etc.
