### ISSUE TITLE
Problems for inference stage

### ISSUE THREAD

**Issue by DrWelles** [microsoft/muzic#12]
i success in data and train stages and meet some problems in inference.
![image](https://user-images.githubusercontent.com/37129535/137569815-5c3280d7-e71f-4fd6-baec-d5f1e9c37892.png)
I meet the similar problem in the train stage, and I use a single GPU to avoid this. However, it didn't work for inference stage.
My environment is Unbuntu 16.04, CUDA 10.2, Python 3.6.12 and others follow requiments.txt. 
Happy to hear your reply

**Comment by StillKeepTry** [comment]
Can you show me your inference scripts?

**Comment by DrWelles** [comment]
> Can you show me your inference scripts?

Ithe bash scripts of infer_lyric.sh and infer_melody.sh in  the songmass folder

**Comment by StillKeepTry** [comment]
And what is your fairseq version?

**Comment by DrWelles** [comment]
> And what is your fairseq version?

as requirement.txt: fairseq==0.10.0

**Comment by StillKeepTry** [comment]
@DrWelles Can you update fairseq to 0.10.2 and have a try?

**Comment by DrWelles** [comment]
> @DrWelles Can you update fairseq to 0.10.2 and have a try?

many thanks! it works fine!
