### ISSUE TITLE
not able to install requirements.txt file for getmusic on windows

### ISSUE THREAD

**Issue by kotaxyz** [microsoft/muzic#123]
hello there ,thanks alot for this awesome tool , im experiencing some problem installing requirements.txt file , i tried to do it using anaconda but i get this error 
(venv) C:\Users\ma\anaconda3\muzic\getmusic>pip install -r requirements.txt
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

even after fixing it and making == it still throws an error 

ERROR: Invalid requirement: '_libgcc_mutex==0.1=main' (from line 4 of requirements.txt)

**Comment by maemoKKK** [comment]
> it

How did fix it?
I run 'pip install -r requirements.txt' in ubuntu terminal, it shows ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt).

I install anaconda3, it still not work
