### ISSUE TITLE
[getmusic] promot cannot import name 'RoFormerPreTrainedModel'

### ISSUE THREAD

**Issue by maemoKKK** [microsoft/muzic#132]
(base) avr@avr-Alienware-17-R3:~/Downloads/muzic/getmusic$ conda create --name CVBR --file requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

    threadpoolctl==3.1.0=pypi_0
    wcwidth==0.2.6=pypi_0
    aiosignal==1.3.1=pypi_0
    pyyaml==6.0=pypi_0
    contourpy==1.0.7=pypi_0
    kiwisolver==1.4.4=pypi_0
    matplotlib==3.7.1=pypi_0
    async-timeout==4.0.2=pypi_0
    attrs==22.2.0=pypi_0
    google-auth-oauthlib==0.4.6=pypi_0
    transformers==4.27.4=pypi_0
    pytorch-lightning==2.0.1=pypi_0
    tensorboard==2.12.0=pypi_0
    fonttools==4.39.2=pypi_0
    torchaudio==0.12.1+cu113=pypi_0
    numpy==1.20.0=pypi_0
    sacrebleu==2.3.1=pypi_0
    mypy==1.1.1=pypi_0
    cython==0.29.34=pypi_0
    lxml==4.9.2=pypi_0
    imageio==2.27.0=pypi_0
    joblib==1.2.0=pypi_0
    importlib-resources==5.12.0=pypi_0
    markdown==3.4.3=pypi_0
    regex==2023.3.23=pypi_0
    cycler==0.11.0=pypi_0
    requests==2.28.2=pypi_0
    scikit-learn==1.2.2=pypi_0
    oauthlib==3.2.2=pypi_0
    rapidfuzz==2.15.1=pypi_0
    omegaconf==2.3.0=pypi_0
    mypy-extensions==1.0.0=pypi_0
    torchvision==0.13.1+cu113=pypi_0
    qudida==0.0.4=pypi_0
    charset-normalizer==3.1.0=pypi_0
    tomli==2.0.1=pypi_0
    filelock==3.10.7=pypi_0
    tqdm==4.65.0=pypi_0
    mido==1.2.10=pypi_0
    albumentations==1.3.0=pypi_0
    antlr4-python3-runtime==4.9.3=pypi_0
    dataclasses==0.6=pypi_0
    multidict==6.0.4=pypi_0
    pytest==7.2.2=pypi_0
    networkx==3.0=pypi_0
    grpcio==1.51.3=pypi_0
    tensorboard-plugin-wit==1.8.1=pypi_0
    packaging==23.0=pypi_0
    pluggy==1.0.0=pypi_0
    cachetools==5.3.0=pypi_0
    idna==3.4=pypi_0
    exceptiongroup==1.1.1=pypi_0
    lit==16.0.1=pypi_0
    colorama==0.4.6=pypi_0
    lazy-loader==0.2=pypi_0
    tabulate==0.9.0=pypi_0
    protobuf==4.22.1=pypi_0
    markupsafe==2.1.2=pypi_0
    cffi==1.15.1=pypi_0
    iniconfig==2.0.0=pypi_0
    six==1.16.0=pypi_0
    einops==0.6.0=pypi_0
    pillow==9.4.0=pypi_0
    fairseq==0.10.2=pypi_0
    absl-py==1.4.0=pypi_0
    werkzeug==2.2.3=pypi_0
    ftfy==6.1.1=pypi_0
    yarl==1.8.2=pypi_0
    python-dateutil==2.8.2=pypi_0
    huggingface-hub==0.13.4=pypi_0
    pycparser==2.21=pypi_0
    torch==1.12.1+cu113=pypi_0
    tifffile==2023.3.21=pypi_0
    triton==2.1.0=dev_0
    rsa==4.9=pypi_0
    pywavelets==1.4.1=pypi_0
    lightning-utilities==0.8.0=pypi_0
    fsspec==2023.3.0=pypi_0
    pyasn1==0.4.8=pypi_0
    tensorboard-data-server==0.7.0=pypi_0
    torchmetrics==0.11.4=pypi_0
    importlib-metadata==6.1.0=pypi_0
    cmake==3.26.3=pypi_0
    hydra-core==1.3.2=pypi_0
    tokenizers==0.13.3=pypi_0
    pycryptodomex==3.17=pypi_0
    typing-extensions==4.5.0=pypi_0
    blobfile==2.0.1=pypi_0
    path==16.6.0=pypi_0
    frozenlist==1.3.3=pypi_0
    zipp==3.15.0=pypi_0
    dall-e==0.1=pypi_0
    portalocker==2.7.0=pypi_0
    requests-oauthlib==1.3.1=pypi_0
    aiohttp==3.8.4=pypi_0
    opencv-python-headless==4.7.0.72=pypi_0
    scipy==1.9.1=pypi_0
    urllib3==1.26.15=pypi_0
    pyasn1-modules==0.2.8=pypi_0
    scikit-image==0.20.0=pypi_0
    google-auth==2.16.3=pypi_0
    levenshtein==0.20.9=pypi_0
    pyparsing==3.0.9=pypi_0

Current channels:

    https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/linux-64
    https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/noarch
    https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/linux-64
    https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch
    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/linux-64
    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
    https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/linux-64
    https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/noarch
    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64
    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
    https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-64
    https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
    https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-64
    https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
    https://repo.anaconda.com/pkgs/main/linux-64
    https://repo.anaconda.com/pkgs/main/noarch
    https://repo.anaconda.com/pkgs/r/linux-64
    https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org

and use the search bar at the top of the page

**Comment by maemoKKK** [comment]
I'm so confused by reqirement.txt. it's deffierent with the one in muzic root folder. 

reqirement.txt looks like generated by conda.

So, I install anaconda and:
conda create -n CVBR python=3.8
conda install --name CVBR --file  reqirement.txt 
then it shows packagesNotFound, I think it‘s due to conda.

Can you show me a way to install your reqirement.txt?

I'm really need this

**Comment by maemoKKK** [comment]
(base) avr@avr-Alienware-17-R3:~/Downloads/muzic/getmusic$ conda create --name CVBR --file requirements.txt 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - threadpoolctl==3.1.0=pypi_0
  - wcwidth==0.2.6=pypi_0
  - aiosignal==1.3.1=pypi_0
  - pyyaml==6.0=pypi_0
  - contourpy==1.0.7=pypi_0
  - kiwisolver==1.4.4=pypi_0
  - matplotlib==3.7.1=pypi_0
  - async-timeout==4.0.2=pypi_0
  - attrs==22.2.0=pypi_0
  - google-auth-oauthlib==0.4.6=pypi_0
  - transformers==4.27.4=pypi_0
  - pytorch-lightning==2.0.1=pypi_0
  - tensorboard==2.12.0=pypi_0
  - fonttools==4.39.2=pypi_0
  - torchaudio==0.12.1+cu113=pypi_0
  - numpy==1.20.0=pypi_0
  - sacrebleu==2.3.1=pypi_0
  - mypy==1.1.1=pypi_0
  - cython==0.29.34=pypi_0
  - lxml==4.9.2=pypi_0
  - imageio==2.27.0=pypi_0
  - joblib==1.2.0=pypi_0
  - importlib-resources==5.12.0=pypi_0
  - markdown==3.4.3=pypi_0
  - regex==2023.3.23=pypi_0
  - cycler==0.11.0=pypi_0
  - requests==2.28.2=pypi_0
  - scikit-learn==1.2.2=pypi_0
  - oauthlib==3.2.2=pypi_0
  - rapidfuzz==2.15.1=pypi_0
  - omegaconf==2.3.0=pypi_0
  - mypy-extensions==1.0.0=pypi_0
  - torchvision==0.13.1+cu113=pypi_0
  - qudida==0.0.4=pypi_0
  - charset-normalizer==3.1.0=pypi_0
  - tomli==2.0.1=pypi_0
  - filelock==3.10.7=pypi_0
  - tqdm==4.65.0=pypi_0
  - mido==1.2.10=pypi_0
  - albumentations==1.3.0=pypi_0
  - antlr4-python3-runtime==4.9.3=pypi_0
  - dataclasses==0.6=pypi_0
  - multidict==6.0.4=pypi_0
  - pytest==7.2.2=pypi_0
  - networkx==3.0=pypi_0
  - grpcio==1.51.3=pypi_0
  - tensorboard-plugin-wit==1.8.1=pypi_0
  - packaging==23.0=pypi_0
  - pluggy==1.0.0=pypi_0
  - cachetools==5.3.0=pypi_0
  - idna==3.4=pypi_0
  - exceptiongroup==1.1.1=pypi_0
  - lit==16.0.1=pypi_0
  - colorama==0.4.6=pypi_0
  - lazy-loader==0.2=pypi_0
  - tabulate==0.9.0=pypi_0
  - protobuf==4.22.1=pypi_0
  - markupsafe==2.1.2=pypi_0
  - cffi==1.15.1=pypi_0
  - iniconfig==2.0.0=pypi_0
  - six==1.16.0=pypi_0
  - einops==0.6.0=pypi_0
  - pillow==9.4.0=pypi_0
  - fairseq==0.10.2=pypi_0
  - absl-py==1.4.0=pypi_0
  - werkzeug==2.2.3=pypi_0
  - ftfy==6.1.1=pypi_0
  - yarl==1.8.2=pypi_0
  - python-dateutil==2.8.2=pypi_0
  - huggingface-hub==0.13.4=pypi_0
  - pycparser==2.21=pypi_0
  - torch==1.12.1+cu113=pypi_0
  - tifffile==2023.3.21=pypi_0
  - triton==2.1.0=dev_0
  - rsa==4.9=pypi_0
  - pywavelets==1.4.1=pypi_0
  - lightning-utilities==0.8.0=pypi_0
  - fsspec==2023.3.0=pypi_0
  - pyasn1==0.4.8=pypi_0
  - tensorboard-data-server==0.7.0=pypi_0
  - torchmetrics==0.11.4=pypi_0
  - importlib-metadata==6.1.0=pypi_0
  - cmake==3.26.3=pypi_0
  - hydra-core==1.3.2=pypi_0
  - tokenizers==0.13.3=pypi_0
  - pycryptodomex==3.17=pypi_0
  - typing-extensions==4.5.0=pypi_0
  - blobfile==2.0.1=pypi_0
  - path==16.6.0=pypi_0
  - frozenlist==1.3.3=pypi_0
  - zipp==3.15.0=pypi_0
  - dall-e==0.1=pypi_0
  - portalocker==2.7.0=pypi_0
  - requests-oauthlib==1.3.1=pypi_0
  - aiohttp==3.8.4=pypi_0
  - opencv-python-headless==4.7.0.72=pypi_0
  - scipy==1.9.1=pypi_0
  - urllib3==1.26.15=pypi_0
  - pyasn1-modules==0.2.8=pypi_0
  - scikit-image==0.20.0=pypi_0
  - google-auth==2.16.3=pypi_0
  - levenshtein==0.20.9=pypi_0
  - pyparsing==3.0.9=pypi_0

Current channels:

  - https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/noarch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/noarch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/noarch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by maemoKKK** [comment]
ubuntu 18.04 
cuda 11.3
Could give me some tips?

**Comment by trestad** [comment]
Environment setups are updated in the readme, please refer to it. Hope this can help.

**Comment by maemoKKK** [comment]
thanks,  missing  scipy,
and must install numpy 1.20.0

it works

**Comment by maemoKKK** [comment]
two questions：
1. does getmusic can inference all the midi files in https://musescore.com/?
2. How should I understand "Check MIDI program ID: GETMusic supports the following instruments (MIDI program): '0': piano, '25':guitar, '32':bass, '48':string, '80':lead melody. You do not need to worry about the percussion program." do you mean what I need check is the num 0, 25, 32, 48 and 80?

**Comment by trestad** [comment]
Please show me more detailed chord error.

Note that in MIDI, an instrument is referred to as a program, and each program is assigned a unique number. You can find a comprehensive list of program numbers at this link: https://midiprog.com/program-numbers/. For instance, according to the table on that webpage, 'Acoustic Grand Piano' is assigned program number 1, while 'Bright Acoustic Piano' is assigned program number 2, even though both instruments are pianos. In GETMusic, we default to using 'Acoustic Grand Piano,' which corresponds to program number 0 in our code, since we start counting from while in the linked table, the numbering starts from 1. As another example, when we mention '80':lead melody, it means that the lead melody should be played using the 'Square Lead' instrument, which is the 81st program listed in the link.

The chord error you encountered is likely due to the fact that neither track in your input MIDI file corresponds to a program number supported by GETMusic. As a result, all tracks are filtered out. Since GETMusic doesn't receive any input and chord guidance is enabled by default, it cannot infer chords and raises an error. To address this issue, you have two options: you can modify the input processing in the code or adjust the program number in your input MIDI file. I hope this response addresses your first question.

**Comment by maemoKKK** [comment]
Thanks for your reply， I will raise a new topic to discuss in order to let more people know.
