### ISSUE TITLE
[SongMASS]请问如何解决未配对的歌词和旋律数据

### ISSUE THREAD

**Issue by liuasdeu** [microsoft/muzic#141]
请问在SongMASS项目中，如何运用未配对的歌词和旋律数据训练模型

**Comment by Amarelen** [comment]
> 请问在SongMASS项目中，如何运用未配对的歌词和旋律数据训练模型

您好！抱歉打扰，因为作者提供的checkpoint链接失效了，想请问一下您是否有曾经作者提供的训练好的模型存档？谢谢您！

**Comment by liuasdeu** [comment]
不好意思，现在才看到您的信息，现在我看到预训练模型可以下载了，当时我也是不能下载预训练模型


L
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/muzic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/muzic] [SongMASS]请问如何解决未配对的歌词和旋律数据 (Issue #141)





  
请问在SongMASS项目中，如何运用未配对的歌词和旋律数据训练模型
  
您好！抱歉打扰，因为作者提供的checkpoint链接失效了，想请问一下您是否有曾经作者提供的训练好的模型存档？谢谢您！

**Comment by liuasdeu** [comment]
不好意思，现在才看到您的信息，现在我看到预训练模型可以下载了，当时我也是不能下载预训练模型，很抱歉没有帮到你，祝你生活愉快！


L
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "microsoft/muzic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/muzic] [SongMASS]请问如何解决未配对的歌词和旋律数据 (Issue #141)





  
请问在SongMASS项目中，如何运用未配对的歌词和旋律数据训练模型
  
您好！抱歉打扰，因为作者提供的checkpoint链接失效了，想请问一下您是否有曾经作者提供的训练好的模型存档？谢谢您！
