### ISSUE TITLE
[MusicBERT] Pretrained checkpoint models' access is not permitted 

### ISSUE THREAD

**Issue by PawitsapakA** [microsoft/muzic#142]
Hello,

Are MusicBERT pretrained models still publicly available? Since I tried to download them from https://github.com/microsoft/muzic/tree/main/musicbert#21-pre-training but the access is denied.

Thanks in advance.

**Comment by MHZ9825** [comment]
I' ve met the same problem, could u contact me if the problem is solved ?  Thanks in advance!

**Comment by mlzeng** [comment]
Hello, @PawitsapakA  @MHZ9825 . Replace the substring `msramldl` in the download link to `msramllasc` seems working for now.

**Comment by MHZ9825** [comment]
> Hello, @PawitsapakA @MHZ9825 . Replace the substring `msramldl` in the download link to `msramllasc` seems working for now.

Problem solved， Thanks a lot ！！！

**Comment by PawitsapakA** [comment]
> Hello, @PawitsapakA @MHZ9825 . Replace the substring `msramldl` in the download link to `msramllasc` seems working for now.

It's working. Thanks for the help!
