### ISSUE TITLE
Documentation to create a dataset for deeprapper in another languages

### ISSUE THREAD

**Issue by eddydecena** [microsoft/muzic#15]
I would like to know if there is any documentation of the creation of the dataset in order to create a dataset for other languages.

**Comment by lxueaa** [comment]
Currently, we do not have the document of creating the dataset for other languages. But if you want to apply it to other languages, you can use your own tokenizers for vocabulary, vowels, and so on. Furthermore, you need to rewrite the function `process_lyrics()`, `parse_lyrics()`, `prepare_lyrics()`, `read_lyrics()` in the `prepare_train_data.py`. We provide the examples of data before and after processing in `./deeprapper/data/lyrics/lyrics_examples/`.
