### ISSUE TITLE
[MusicBERT] Can't download pretrained checkpoints

### ISSUE THREAD

**Issue by malcolmsailor** [microsoft/muzic#158]
I have the same issue described in #142: I cannot download the pretrained checkpoints linked at https://github.com/microsoft/muzic/tree/main/musicbert#21-pre-training.

It seems that @mlzeng's suggestion of using `msramllasc` in the download paths has been applied in the documentation, however, I still get the following permission error when trying to download:
```
> wget https://msramllasc.blob.core.windows.net/modelrelease/checkpoint_last_musicbert_small.pt
--2023-08-11 13:46:23--  https://msramllasc.blob.core.windows.net/modelrelease/checkpoint_last_musicbert_small.pt
Resolving msramllasc.blob.core.windows.net (msramllasc.blob.core.windows.net)... 20.209.34.164
Connecting to msramllasc.blob.core.windows.net (msramllasc.blob.core.windows.net)|20.209.34.164|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-08-11 13:46:24 ERROR 409: Public access is not permitted on this storage account..
```

Help would be appreciated. Thanks!

**Comment by mlzeng** [comment]
Hello @malcolmsailor , I have updated the links.

**Comment by malcolmsailor** [comment]
Thank you, it works now!
