### ISSUE TITLE
How did I can get the pickle?#PDAugment

### ISSUE THREAD

**Issue by YoungKang1222** [microsoft/muzic#20]
![image](https://user-images.githubusercontent.com/30460985/139227982-0526ce2c-7c9a-4a9f-b770-c964565e7afd.png)

Excuse, I didn't understand the list meaning, and could you explaint the 'split position'?
it represent the phone length? or the phone's mfcc mapping value?

**Comment by YoungKang1222** [comment]
![image](https://user-images.githubusercontent.com/30460985/139610453-52f735f2-ced9-487a-b28a-98e04a100835.png)

In 3.2, authors mention the grouping techniques.

**Comment by actuy** [comment]
The start position of each phoneme can be loaded from the TextGrid file, which is described in s or ms. Then you can change it to frame according to your sampling rate and hop size. For example, if the sampling rate is 16k and the hop size is 256, one frame is corresponding to 16ms. The number of position sequences in the pickle file is the frame number.

**Comment by YoungKang1222** [comment]
Thanks a lot. I got whar you mean.
