### ISSUE TITLE
Normalizing OctupleMIDI between [-1., 1.]

### ISSUE THREAD

**Issue by saravanr** [microsoft/muzic#21]
Hi Muzic Team,

OctupleMIDI is incredibly cool way to encode MIDI content. I am working on the LMD data set and am able to convert `MIDI->OctupleMIDI->MIDI`. However in-order to train my model, I need to ensure the values are normalized between `[-1., 1.]`.

I looked at your paper and inferred that, the following are the max-values for the different columns in OctupleMIDI:

```
    [Time Sig, Tempo, Bar, Position, Instrument, Pitch, Duration, Velocity]
    [254, [16-256], [256], [256], [128], 128, 128, 128]
```
However on analyzing the data I have, I see the max values of OctupleMIDI encoded files are as follows:

```
    [Time Sig, Tempo, Bar, Position, Instrument, Pitch, Duration, Velocity]
    [9280., 127., 128., 255., 127., 31., 157., 48.]
```
I am not sure if this is a because of corrupt MIDI files or there is something else amiss. Essentially I am trying to find the max range of these values so I can use that to normalize the encoding.

Is this the right way to do it? Any help would be much appreciated!

Thanks!

**Comment by mlzeng** [comment]
The types of values in an encoded tuple should be (you can refer to the code):
(0:Measure, 1:Pos, 2:Program, 3:Pitch, 4:Duration, 5:Velocity, 6:TimeSig, 7:Tempo)

The corresponding ranges of values in an encoded tuple should be:
([0, 255], [0, 127], [0, 128], [0, 255], [0, 127], [0, 31], [0, 253], [0, 48])

The maximum possible values may not occur in real-world music datasets. So what you get looks good to me.

Be aware that musical notes of percussion instruments are represented as (Program=128, Pitch=[128,255]). The "pitches" in percussion notes mean percussion type but not frequency. You may want to filter them out in your case.
