### ISSUE TITLE
miss argument

### ISSUE THREAD

**Issue by pikapi111** [microsoft/muzic#22]
when i bash generate.sh,  the function  " get_sentence_pinyin_finals() " input  "raw_text", but this function has two parameters when it is defined

TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'

**Comment by wmj9711** [comment]
Excuse me, I have the same problem with you. Have you solved it?

**Comment by wmj9711** [comment]
> when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
> 
> TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'

Excuse me, I have the same problem with you. Have you solved it?

**Comment by pikapi111** [comment]
> > when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
> > TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'
> 
> Excuse me, I have the same problem with you. Have you solved it?

没呢兄弟，他写了valid_finals，但是没有invalids_finals，我不知道是没写还是我没注意到。。。

**Comment by wmj9711** [comment]
难受啊，兄弟，关键是不知道怎么改这个，是纯粹的没有，我麻了&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/muzic] miss argument (Issue #22)





   
when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
 TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'
  
Excuse me, I have the same problem with you. Have you solved it?
  
没呢兄弟，他写了valid_finals，但是没有invalids_finals，我不知道是没写还是我没注意到。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pikapi111** [comment]
> 难受啊，兄弟，关键是不知道怎么改这个，是纯粹的没有，我麻了&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月20日(星期一) 晚上9:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [microsoft/muzic] miss argument (Issue #22) when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals' Excuse me, I have the same problem with you. Have you solved it? 没呢兄弟，他写了valid_finals，但是没有invalids_finals，我不知道是没写还是我没注意到。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

没办法，我这几个月了也没人回复，换个别的看看吧

**Comment by lxueaa** [comment]
> when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
> 
> TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'

This argument is used to just cache invalid finals which are found during processing text. You can use the function by just giving an empty dict to the `invalids_finals`, like `get_sentence_pinyin_finals(line=line, invalids_finals={})`

**Comment by pikapi111** [comment]
> 

Thank you !

**Comment by pikapi111** [comment]
> > when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
> > TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'
> 
> This argument is used to just cache invalid finals which are found during processing text. You can use the function by just giving an empty dict to the `invalids_finals`, like `get_sentence_pinyin_finals(line=line, invalids_finals={})`

thank you!

**Comment by lxueaa** [comment]
> Thank you !

Sorry for late reply!

**Comment by pikapi111** [comment]
> > Thank you !
> 
> Sorry for late reply!

It doesn't matter, thanks!

**Comment by wmj9711** [comment]
> > when i bash generate.sh, the function " get_sentence_pinyin_finals() " input "raw_text", but this function has two parameters when it is defined
> > TypeError: get_sentence_pinyin_finals() missing 1 required positional argument: 'invalids_finals'
> 
> This argument is used to just cache invalid finals which are found during processing text. You can use the function by just giving an empty dict to the `invalids_finals`, like `get_sentence_pinyin_finals(line=line, invalids_finals={})`

Thanks!!
