### ISSUE TITLE
Dictionary Error for PDAugment while aligning

### ISSUE THREAD

**Issue by ivylijingru** [microsoft/muzic#23]
I've seen the previous issue that says we should manually align the phonemes via MFA alignment tool. 
While when I try the official example with the pretrained model provided, I've got the following error:

> dictionary phones: {'th', 'b', 'v', 'ch', 'sh', 'p', 'ey', 's', 'k', 'jh', 'ow', 'hh', 'ah', 'oy', 'd', 'uh', 'm', 'dh', 'ax', 'iy', 'ih', 'zh', 'ae', 'er', 'y', 'l', 'w', 'ng', 'aw', 'n', 'aa', 'g', 'ao', 'r', 't', 'eh', 'uw', 'f', 'ay', 'z'}
model phones: {'IY0', 'AO2', 'AY1', 'IY1', 'AE2', 'UH2', 'M', 'AA0', 'UW1', 'F', 'N', 'EH0', 'AO1', 'G', 'OY0', 'AE1', 'UW0', 'Z', 'ER2', 'CH', 'NG', 'AH2', 'ER1', 'JH', 'OW0', 'UH0', 'OY1', 'P', 'SH', 'EY2', 'DH', 'AH1', 'ZH', 'AY0', 'AW0', 'AE0', 'AA2', 'T', 'TH', 'EY0', 'UW2', 'V', 'AA1', 'OW2', 'S', 'EY1', 'IY2', 'R', 'AY2', 'EH1', 'AH0', 'EH2', 'IH2', 'L', 'K', 'UH1', 'AW1', 'AO0', 'AW2', 'D', 'OY2', 'W', 'B', 'Y', 'IH1', 'HH', 'OW1', 'IH0', 'ER0'}
There were phones in the dictionary that do not have acoustic models: aa, ae, ah, ao, aw, ax, ay, b, ch, d, dh, eh, er, ey, f, g, hh, ih, iy, jh, k, l, m, n, ng, ow, oy, p, r, s, sh, t, th, uh, uw, v, w, y, z, zh

Is there a way to convert between these phones? Or is there another model that takes dictionary phones as input? Thanks.

ps. It seems that 'ax' does not exist in the model phones.

**Comment by actuy** [comment]
MFA provided pre-trained acoustic models using their specific lexicon. 
You can train an acoustic model by yourself with your own corpus and phoneme set (refer to https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/train_acoustic_model.html#train-acoustic-model and https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#training-a-new-acoustic-model-on-a-corpus). 
If you want to use the pre-trained acoustic models still, you can use the official LibriSpeech lexicon (refer to https://drive.google.com/open?id=1dAvxdsHWbtA1ZIh3Ex9DPn9Nemx9M1-L), which is consistent with the above 'model phones'.

**Comment by ivylijingru** [comment]
Thanks for your suggestion. I'll try to train the alignment model.
