### ISSUE TITLE
Does PDAugment capable of augmenting Mandarin?

### ISSUE THREAD

**Issue by YoungKang1222** [microsoft/muzic#24]
Excuse, I want to transfer PDAugment to Mandarin. I wander is the difference with English the text2phone?

**Comment by actuy** [comment]
In fact, we haven't conducted experiments on Mandarin, but the idea is the same. You can still use phonemizer to get the phone of lyrics in Mandarin, and then use MFA to get the alignment.
A difference is that a character in Mandarin is a syllable, so it will be easier to obtain the syllable-level alignment.

**Comment by YoungKang1222** [comment]
yeah, as you say! 
But the phone of phonemizer's resutl doesn't match the MFA'result.
For example, the phone of lyrics maybe 5, but the phone of MFA maybe 4, is that right?
If so, the augmenting is failure. how do you handle this?

**Comment by actuy** [comment]
You can train an acoustic model by yourself with your own corpus and phoneme set (refer to https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/train_acoustic_model.html#train-acoustic-model and https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#training-a-new-acoustic-model-on-a-corpus).

**Comment by YoungKang1222** [comment]
I 'll try. thanks for your suggestion!

**Comment by My-captain** [comment]
> I 'll try. thanks for your suggestion!

Hi, YoungKang. Have you try PDAugment on mandarin dataset?
