### ISSUE TITLE
HiFiSinger code release?

### ISSUE THREAD

**Issue by gabriel-lavoie-viau** [microsoft/muzic#25]
Hi, I was wondering if you were planning on releasing the code for HiFiSinger anytime soon? I would be very much interested in experimenting with it.

Thank you!

**Comment by tan-xu** [comment]
Hi, thanks for your interests in HiFiSinger. Since it is closely related to our product, it will be a long and complicated journey for open-source. We will try the best to make our future research work public.

**Comment by zhangsanfeng86** [comment]
@tan-xu how to get the training data ,Could you give some advice?

**Comment by ain-soph** [comment]
@gabriel-lavoie-viau  
Hi, I'm also looking for it. I only find a 3rd-party implementation here without training data:  
https://github.com/CODEJIN/HiFiSinger

Please kindly share with me if you have found any other resources.

**Comment by gabriel-lavoie-viau** [comment]
@ain-soph Thanks for the link, I'm curious, did you try it? 

For my part, I went for an adaptation of the DDSP library from Magenta made for singing voices : https://github.com/gianmarcohutter/ddsp_gm2.

I trained a model with this dataset : https://zenodo.org/record/1193957#.Yf7E4erMLm4. It is not perfect but it's interesting.
