### ISSUE TITLE
[musicBERT] encoding_to_MIDI has a problem?

### ISSUE THREAD

**Issue by rgb000000** [microsoft/muzic#26]
Hello, I am trying to use the wonderful octupleMIDI representation.
First, I get `encoding` by `MIDI_to_encoding`. Then, I restore it to midi by `encoding_to_MIDI`. But, there is a problem with the duration of some notes, like this.

I find the restored midi file will be right, if filtering out the notes whose duration is 0 in `encoding_to_MIDI` function. 
Maybe there is a bug in `miditoolkit(0.1.14, 0.1.15)`?

![image](https://user-images.githubusercontent.com/26807648/143020424-4d00f0fe-86ee-456a-845c-17cc9aaf4924.png)

This is my solution(in `preprocess.py`):
![image](https://user-images.githubusercontent.com/26807648/143023327-093bbed5-e899-451f-85a6-506857e3fb25.png)

**Comment by mlzeng** [comment]
Thanks very much for your bug report. Discarding zero-duration notes may result in a significant loss of musical information. This issue can be efficiently fixed by changing zero durations to the smallest possible non-zero durations.
