### ISSUE TITLE
[PDAugment] What does the phoneme level alignment pickle file contain?

### ISSUE THREAD

**Issue by teowz46** [microsoft/muzic#28]
Hi PDAugment team, just a quick question about the pickle file generated during the phoneme level alignment stage. In the example on the README 
```
{
    "174-168635-0000.wav" : [0, 12, 18, 20...],
    "174-168635-0001.wav" : [0, 12, 27, 35...],
    "174-168635-0002.wav" : [0, 13, 26, 33...],
    ...
}
```
what do the lists such as [0, 12, 18, 20, ...] represent? Do they represent the milliseconds for the split positions between adjacent phonemes?

**Comment by actuy** [comment]
Hi, you can refer to this issue https://github.com/microsoft/muzic/issues/20.
