### ISSUE TITLE
whether it's possible to provide or release a lyric-to-rhythm of checkpoint?

### ISSUE THREAD

**Issue by DrWelles** [microsoft/muzic#29]
is it possible to release a checkpoint of lyric-to-rhythm model? This doesn't seem to have copyright issues

**Comment by jzq2000** [comment]
Sure. I will provide it in some days.

**Comment by jzq2000** [comment]
Hi. The checkpoints of EN and ZH lyric-to-rhythm models in Telemelody are now available. We also provide their dictionary in `training/lyric2rhythm/dict` for your reference.

**Comment by DrWelles** [comment]
Thanks for lyric2rhythm model. However, I meet some problems while I infer with this. Could you help?
cmd: python infer_zh.py zh t2m test zh_save
file structure:
![image](https://user-images.githubusercontent.com/37129535/150626004-fa6633a0-c0f6-485f-a539-d7e9da31861e.png)

![image](https://user-images.githubusercontent.com/37129535/150623720-9b2094c0-2b8f-40e3-9fd8-4e0eae7b7899.png)

**Comment by jzq2000** [comment]
Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue.  The issue seems to be associated with the file path and perhaps you can double-check it.

**Comment by DrWelles** [comment]
> Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.

may I ask the fairseq version you used? I still find errors when load lyric2rhythm model as follows:
![image](https://user-images.githubusercontent.com/37129535/150749006-1b09f69c-683c-4c6a-bfaf-56305be1f25c.png)
output of logging as follows:
![image](https://user-images.githubusercontent.com/37129535/150749150-016bfa9f-58c7-432e-91e5-2abcabf9707c.png)
it seems that when variable "state" loads from checkpoint missing the value of "args", which results in the default value of "args" make it None and unable to use function "setattr(args, arg_name, arg_val)"
Could you please check it ？ And my fairseq version is fairseq==0.10.0 as requirement.txt.

**Comment by DrWelles** [comment]
> Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.

Thanks! I find that it's due to problem of fairseq rather than checkpoint issue.

if others have the same problem, following cmd may help:
pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d

**Comment by BILLXZY1215** [comment]
@DrWelles Hi, can you share the `t2m/checkpoint_best.pt` as well? Thanks in advance.

**Comment by DrWelles** [comment]
> > How? Though it's easy to train this model with released code if you have a GPU
> 
> Yes, can you share a link on google drive or Baidu Wangpan? Currently, my machine only supports CPU and it seems tough work...

链接：https://pan.baidu.com/s/1mUE8qFbmT7Mfo3CyfaK-IA 
提取码：78lq

**Comment by BILLXZY1215** [comment]
> > > How? Though it's easy to train this model with released code if you have a GPU
> > 
> > 
> > Yes, can you share a link on google drive or Baidu Wangpan? Currently, my machine only supports CPU and it seems tough work...
> 
> 链接：https://pan.baidu.com/s/1mUE8qFbmT7Mfo3CyfaK-IA 提取码：78lq

Thanks a lot!

**Comment by leochang0131** [comment]
> > Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.
> 
> Thanks! I find that it's due to problem of fairseq rather than checkpoint issue.
> 
> if others have the same problem, following cmd may help: pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d

hi, I try to run the command you provided here, but it seems to have the problem shown below. Since I'm also in China, I wonder if you have encountered the same problem and how you fixed it. Big thanks in advance!

![Screen Shot 2022-04-03 at 10 08 09 AM](https://user-images.githubusercontent.com/39736282/161408137-3d9b9a7d-ffc2-41b6-8609-83b8000651da.png)

**Comment by leochang0131** [comment]
> > > Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.
> > 
> > 
> > Thanks! I find that it's due to problem of fairseq rather than checkpoint issue.
> > if others have the same problem, following cmd may help: pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d
> 
> hi, I try to run the command you provided here, but it seems to have the problem shown below. Since I'm also in China, I wonder if you have encountered the same problem and how you fixed it. Big thanks in advance!
> 
> ![Screen Shot 2022-04-03 at 10 08 09 AM](https://user-images.githubusercontent.com/39736282/161408137-3d9b9a7d-ffc2-41b6-8609-83b8000651da.png)

I solved it by following the instructions [here](https://www.zhihu.com/question/27159393) , 
`git config --global --unset http.proxy
git config --global --unset https.proxy
git config --global http.https://github.com.proxy socks5://127.0.0.1:1086
git config --global https.https://github.com.proxy socks5://127.0.0.1:1086`

**Comment by li-car-fei** [comment]
> > Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.
> 
> Thanks! I find that it's due to problem of fairseq rather than checkpoint issue.
> 
> if others have the same problem, following cmd may help: pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d

Can you provide specific code branches? I need to download that branch and install it myself

**Comment by feiyuehchen** [comment]
For anyone who can't download via the link: 
`pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d`

You may consider this one:
`pip install soundfile git+https://github.com/facebookresearch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d`

**Comment by MuHyeonSon** [comment]
> > > > Hi! I run the same command in the terminal with the same file structure, but I can't reproduce the issue. The issue seems to be associated with the file path and perhaps you can double-check it.
> > > 
> > > 
> > > Thanks! I find that it's due to problem of fairseq rather than checkpoint issue.
> > > if others have the same problem, following cmd may help: pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d
> > 
> > 
> > hi, I try to run the command you provided here, but it seems to have the problem shown below. Since I'm also in China, I wonder if you have encountered the same problem and how you fixed it. Big thanks in advance!
> > ![Screen Shot 2022-04-03 at 10 08 09 AM](https://user-images.githubusercontent.com/39736282/161408137-3d9b9a7d-ffc2-41b6-8609-83b8000651da.png)
> 
> I solved it by following the instructions [here](https://www.zhihu.com/question/27159393) , `git config --global --unset http.proxy` `git config --global --unset https.proxy` `git config --global http.https://github.com.proxy socks5://127.0.0.1:1086` `git config --global https.https://github.com.proxy socks5://127.0.0.1:1086`

for anyone who have same issue

- access the following address with web browser
    https://github.com/facebookresearch/fairseq/commit/b8ea8a9b72c82192da07e3377adf4ebbde16716d

- clik the Browse files

- click the Code and then download ZIP

- unzip the downloaded zip file

- Go to the unzip directory

- pip install .
