### ISSUE TITLE
Can you provide a checkpoint for telemelody/template2melody?

### ISSUE THREAD

**Issue by BILLXZY1215** [microsoft/muzic#31]
Hi, thanks for the update on #29. However, can you provide the `telemelody/template2melody`'s checkpoint as well? Thanks in advance.

**Comment by jzq2000** [comment]
Sure.  I will provide it in some days.

**Comment by jzq2000** [comment]
Very sorry for the delay on the response. The template2melody model is available now.

**Comment by Liujingxiu23** [comment]
@jzq2000  hi， where can I download the telemelody pretrained model?

**Comment by jzq2000** [comment]
@Liujingxiu23  Hi, you can refer to the hyperlinks on README.

**Comment by Liujingxiu23** [comment]
@jzq2000  I read the REAME , but did not find any hyperlink to download it.

**Comment by jzq2000** [comment]
I'm sorry for the confusion caused by my vague expression.  Hyperlinks are displayed like this. (Please note ``Here``.)

(UPDATE: [Here](https://msramllasc.blob.core.windows.net/modelrelease/template2melody_best.pt) we provide the template-to-melody model trained on lmd_matched dataset. )

**Comment by Liujingxiu23** [comment]
@jzq2000 thank you!

**Comment by deeplearning4ever** [comment]
Hi @jzq2000,

The links are broken :/ can you update them please ?

(UPDATE: We provide our [EN](https://msramllasc.blob.core.windows.net/modelrelease/lyric2rhythm_en_best.pt) and [ZH](https://msramllasc.blob.core.windows.net/modelrelease/lyric2rhythm_zh_best.pt) checkpoints , and corresponding dictionary in  training/lyric2rhythm/dict.)

(UPDATE: [Here](https://msramllasc.blob.core.windows.net/modelrelease/template2melody_best.pt) we provide the template-to-melody model trained on lmd_matched dataset. )

Thanks

**Comment by jzq2000** [comment]
@deeplearning4ever Thanks a lot. The issue is now resolved.
