### ISSUE TITLE
[telemelody] Training Process Stuck: Train template-to-melody model

### ISSUE THREAD

**Issue by BILLXZY1215** [microsoft/muzic#33]
Hi, I tried training on my own machine, however, it seems stuck on the training process (1.2 (3) Train template-to-melody model).
<img width="1364" alt="截屏2022-02-18 下午3 36 22" src="https://user-images.githubusercontent.com/61944458/154638566-8c236624-8cf5-4c9b-9b72-8ffb1dbd2ff7.png">

Does this relate to my machine settings? It seems that the `lmd_matched` dataset is set up correctly.

P.S. This issue is also related to #31, thanks in advance.

**Comment by jzq2000** [comment]
I guess it is. Maybe you can check [this issue](https://github.com/pytorch/pytorch/issues/46409)
