### ISSUE TITLE
[teleMelody] English Lyrics' Syllables in Inference

### ISSUE THREAD

**Issue by BILLXZY1215** [microsoft/muzic#34]
Hi, I noticed that in the `inference` part, syllable-level lyrics are required. So how could we get the syntax of the correct syllables? Thanks.

**Comment by jzq2000** [comment]
You can get  syllables with the help of [phonemizer](https://github.com/bootphon/phonemizer) (backend: festival)

**Comment by plusoneee** [comment]
Hi, I was using [phonemizer](https://github.com/bootphon/phonemizer) to get syllable-level lyrics. I got difference between my output and [syllable example](https://github.com/microsoft/muzic/blob/main/telemelody/inferrence/data/en/test/syllable.txt). 
Could you please provide the settings of `phone` , `word` and `syllable`? 
Here is the code I use:
```python
phn = phonemize(
    text,
    language='en-us',
    backend='festival',
    separator=Separator(phone='_', word=' ', syllable='@'),
    strip=True,
    preserve_punctuation=True,
    njobs=4
)
```

**Comment by jzq2000** [comment]
@plusoneee  
```python
separator=Separator(phone='_', word=' ', syllable=' @@'),
```

**Comment by AbdullahMustafa040** [comment]
@BILLXZY1215 can we generate Lyrics to song from it?
