### ISSUE TITLE
MusicBert如果要迁移到音乐情感分类上，应该怎么做呢

### ISSUE THREAD

**Issue by 110wuqu** [microsoft/muzic#40]

**Comment by mlzeng** [comment]
简单来说你只需要准备好数据文件夹（假设是 emotion_data_raw）：
label/
    train.label 每行是标签并且与音乐数据一一对应
    valid.label
    test.label
input0/
    train.txt 每行是 OctupleMIDI 格式的 tokens 列表
    valid.txt
    test.txt
    dict.txt
然后跑 binarize_nsp.sh 的脚本把数据集二进制化（得到 emotion_data_bin），然后跑 train_nsp.sh 的脚本开始训练就行了（只需要做一点名字上的修改）。
建议先复现一下原本的分类任务熟悉流程以及理解数据格式。对于情感分类任务，把原本的标签换成情感标签跑一遍同样的流程就行了。
