### ISSUE TITLE
SONGMASS运行完推理后，没有生成lyric.gt、melody.gt、hypo.txt、song_id_test.txt这四个文件

### ISSUE THREAD

**Issue by SSunnyGG** [microsoft/muzic#41]
SONGMASS运行完推理后，没有生成lyric.gt、melody.gt、hypo.txt、song_id_test.txt这四个文件

**Comment by zerzerzerz** [comment]
请问是怎么解决的？我运行了生成旋律的inference，但是似乎没找到生成的文件？

**Comment by NinaTian98369** [comment]
@SSunnyGG 请问是怎么解决的？遇到了同样的问题，谢谢！
