### ISSUE TITLE
关于musicbert的requirement

### ISSUE THREAD

**Issue by fourthbrother** [microsoft/muzic#42]
请问能给出一个单独的关于musicbert运行环境吗，我的python版本在3.6时安装外面的requirement是出现了诸多错误，如下图所示
![image](https://user-images.githubusercontent.com/40535813/159743473-14e32d0b-b02b-491e-a060-dfd0f5732f14.png)

**Comment by mlzeng** [comment]
MusicBERT 只需要安装 pytorch fairseq sklearn miditoolkit matplotlib 这几个包就可以了，如果找不到精确的版本，使用接近的版本也是可以的。

**Comment by fourthbrother** [comment]
ERROR(UNCAUGHT): lmd_full/f/f9e83fc44461d8be8ff9404c20b8da25.mid预处理出现这个错误是什么原因呢
![image](https://user-images.githubusercontent.com/40535813/161993610-560d8993-2d59-497b-a4af-adf8096d0643.png)
对preprocess代码的改动只是将上述代码放到main函数下面，因为使用原来的代码会出现下面的错误
  File "F:\ProgramData\Anaconda3\envs\musicbert\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.



> MusicBERT 只需要安装 torch fairseq sklearn miditoolkit matplotlib 这几个包就可以了，如果找不到精确的版本，使用接近的版本也是可以的。

**Comment by mlzeng** [comment]
是所有预处理都出这个错误吗？数据集里面有少量 MIDI 文件不符合标准格式，会导致解析出错。如果只有少量 MIDI 文件处理出错，是正常现象。

**Comment by fourthbrother** [comment]
> 是所有预处理都出这个错误吗？数据集里面有少量 MIDI 文件不符合标准格式，会导致解析出错。如果只有少量 MIDI 文件处理出错，是正常现象。

是的，所有，运行到最后一个都没成功

**Comment by mlzeng** [comment]
一般推荐在 Linux 环境上面运行程序，我没有在 Windows 环境测试过程序，不过在多个版本的 Linux 环境测试过，都没有遇到问题。如果没有 Linux 服务器的话，可以试试用 Windows 内置的 WSL 之类的方案在 Linux 环境上面运行程序。
