### ISSUE TITLE
musicbert small for classification: cannot import name 'TransformerSentenceEncoder' from 'fairseq.models.roberta'

### ISSUE THREAD

**Issue by WJULYW** [microsoft/muzic#45]
As title said, after i run 'bash train_genre.sh masd 25 4 checkpoints/checkpoint_last_musicbert_small.pt'.
It came out after i figure out last fairseq version issue(https://github.com/microsoft/muzic/issues/37).

**Comment by WJULYW** [comment]
fixed out already, because of the conflict between the fairseq version installed by requirements.txt and the new-stalled version. 
don't need to do an extra process as https://github.com/microsoft/muzic/issues/37, just replace the line of fairseq in the requirements.txt by 'git+https://github.com/pytorch/fairseq@336942734c85791a90baa373c212d27e7c722662#egg=fairseq
'

**Comment by TheFirstMonkey** [comment]
Check out the solution in this repo： https://github.com/facebookresearch/fairseq/issues/1199#issuecomment-605666798
