### ISSUE TITLE
SongMASS如何将生成的melody转换为midi

### ISSUE THREAD

**Issue by zerzerzerz** [microsoft/muzic#50]
想知道有什么方法可以将生成的melody文件转换为可以播放的文件，比如midi

**Comment by DanMoLiuHen** [comment]
> 想知道有什么方法可以将生成的melody文件转换为可以播放的文件，比如midi

我也有同样的疑问，请问你解决了吗

**Comment by zerzerzerz** [comment]
> > 想知道有什么方法可以将生成的melody文件转换为可以播放的文件，比如midi
> 
> 我也有同样的疑问，请问你解决了吗

刚刚你好像在另一个问题下面也问了这个问题吧，我也在那个问题下面问了同样的问题，当时的那个issue的作者给我这样的代码
https://github.com/microsoft/muzic/issues/48#issuecomment-1107871204
最后这样就能生成midi文件了，可以播放

**Comment by DanMoLiuHen** [comment]
是重复问了。感谢您迅速回复。还有一个问题想请教，melody文件是怎么生成的？我是通过执行infer_melody.sh脚本生成，将结果重定向到.txt文件中，如图所示
![image](https://user-images.githubusercontent.com/80100156/200755453-ac9fa9bb-63af-4c33-9329-196a306de931.png)

**Comment by Amarelen** [comment]
> 是重复问了。感谢您迅速回复。还有一个问题想请教，melody文件是怎么生成的？我是通过执行infer_melody.sh脚本生成，将结果重定向到.txt文件中，如图所示 ![image](https://user-images.githubusercontent.com/80100156/200755453-ac9fa9bb-63af-4c33-9329-196a306de931.png)

您好！很抱歉打扰您，想请教一下您是如何自定义输入歌词的？只能把自己的歌词做成同样形式的验证集这样吗？

**Comment by hsuxiang** [comment]
> 是重复问了。感谢您迅速回复。还有一个问题想请教，melody文件是怎么生成的？我是通过执行infer_melody.sh脚本生成，将结果重定向到.txt文件中，如图所示 ![image](https://user-images.githubusercontent.com/80100156/200755453-ac9fa9bb-63af-4c33-9329-196a306de931.png)

哈喽，请问您知道生成的txt文件中，S-、T-、H-、D-都是什么意思吗
