### ISSUE TITLE
[MusicBERT]: Could not infer model type from Namespace (eval_genre.py)

### ISSUE THREAD

**Issue by aspil** [microsoft/muzic#51]
Hello!

I'm trying to run the evaluation script for the genre classification task using the command `python -u eval_genre.py checkpoints/checkpoint_last_musicbert_small.pt topmagd_data_bin/x`, and I'm getting the error below when running `RobertaModel.from_pretrained`:

```
Traceback (most recent call last):
  File "eval_genre.py", line 39, in <module>
    user_dir='musicbert'
  File "/home/aspil/muzic/musicbert/fairseq/fairseq/models/roberta/model.py", line 251, in from_pretrained
    **kwargs,
  File "/home/aspil/muzic/musicbert/fairseq/fairseq/hub_utils.py", line 75, in from_pretrained
    arg_overrides=kwargs,
  File "/home/aspil/muzic/musicbert/fairseq/fairseq/checkpoint_utils.py", line 353, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/aspil/muzic/musicbert/fairseq/fairseq/tasks/fairseq_task.py", line 567, in build_model
    model = models.build_model(args, self)
  File "/home/aspil/muzic/musicbert/fairseq/fairseq/models/__init__.py", line 93, in build_model
    + model_type
AssertionError: Could not infer model type from Namespace(_name='roberta_small', activation_dropout=0.0, activation_fn='gelu', adam_betas='(0.9,0.98)', adam_eps=1e-06, all_gather_list_size=16384, arch='roberta_small', attention_dropout=0.1, azureml_logging=False, batch_size=8, batch_size_valid=8, best_checkpoint_metric='loss', bf16=False, bpe='gpt2', broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='_bar_roberta_small', clip_norm=0.0, cpu=False, criterion='masked_lm', curriculum=0, data='topmagd_data_bin/0/input0', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=8, distributed_wrapper='DDP', dropout=0.1, empty_cache_freq=0, encoder_attention_heads=8, encoder_embed_dim=512, encoder_ffn_embed_dim=2048, encoder_layerdrop=0, encoder_layers=4, encoder_layers_to_keep=None, end_learning_rate=0.0, eos=2, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, freq_weighted_replacement=False, gen_subset='test', heartbeat_timeout=-1, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, leave_unmasked_prob=0.1, load_checkpoint_heads=True, load_checkpoint_on_all_dp_ranks=False, localsgd_frequency=3, log_format='simple', log_interval=100, lr=[0.0005], lr_scheduler='polynomial_decay', mask_multiple_length=1, mask_prob=0.15, mask_stdev=0.0, mask_whole_words=False, max_epoch=0, max_positions=8192, max_tokens=None, max_tokens_valid=None, max_update=125000, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, nprocs_per_node=8, num_shards=1, num_workers=1, optimizer='adam', optimizer_overrides='{}', pad=1, patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, pooler_activation_fn='tanh', pooler_dropout=0.0, power=1.0, profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, random_token_prob=0.1, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=True, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoints/checkpoint_last_bar_roberta_small.pt', sample_break_mode='complete', save_dir='checkpoints', save_interval=1, save_interval_updates=0, scoring='bleu', seed=1, sentence_avg=False, shard_id=0, shorten_data_split_list='', shorten_method='none', skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, spectral_norm_classification_head=False, stop_min_lr=-1.0, stop_time_hours=0, task='masked_lm', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tokens_per_sample=8192, total_num_update='125000', tpu=False, train_subset='train', unk=3, untie_weights_roberta=False, update_freq=[4], use_bmuf=False, use_old_adam=False, user_dir='musicbert', valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, wandb_project=None, warmup_updates=25000, weight_decay=0.01, zero_sharding='none'). Available models: dict_keys(['transformer_lm', 'wav2vec', 'wav2vec2', 'wav2vec_ctc', 'wav2vec_seq2seq']) Requested model type: roberta_small
```
### Environment
- python: Python 3.6.13 :: Anaconda, Inc.
- fairseq: git+https://github.com/pytorch/fairseq@336942734c85791a90baa373c212d27e7c722662#egg=fairseq

Thanks in advance!

**Edit**: When running the above command with the base checkpoint, I get the following: 
```
Traceback (most recent call last):
  File "eval_genre.py", line 39, in <module>
    user_dir='musicbert'
  File "/home/aspil/anaconda3/envs/musicbert_01/lib/python3.6/site-packages/fairseq/models/roberta/model.py", line 251, in from_pretrained
    **kwargs,
  File "/home/aspil/anaconda3/envs/musicbert_01/lib/python3.6/site-packages/fairseq/hub_utils.py", line 75, in from_pretrained
    arg_overrides=kwargs,
  File "/home/aspil/anaconda3/envs/musicbert_01/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 355, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "/home/aspil/anaconda3/envs/musicbert_01/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 115, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/aspil/anaconda3/envs/musicbert_01/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RobertaModel:
        Unexpected key(s) in state_dict: "encoder.sentence_encoder.downsampling.0.weight", "encoder.sentence_encoder.downsampling.0.bias", "encoder.sentence_encoder.upsampling.0.weight", "encoder.sentence_encoder.upsampling.0.bias".
```

I don't know if I messed up something, I'd appreciate any help!

**Comment by mlzeng** [comment]
Hello @aspil 

You should fine-tune the model and use the checkpoint named like `checkpoint_last_genre_topmagd_x_checkpoint_last_musicbert_small.pt`.
Evaluation won't work directly on the original pre-trained model.
You can add ` --save-interval-updates 1 ` to the script to get a working fine-tuned model instantly and get a very low score on evaluation. (for testing only)

**Comment by mlzeng** [comment]
Feel free to ask if you encounter any problems with the experiment

**Comment by aspil** [comment]
I managed to run the whole experiment, and the scores were indeed pretty low.

Thanks a lot for the help!

**Comment by tripathiarpan20** [comment]
Hi @mlzeng and @aspil! 

Really amazed by and thankful for this work (MusicBERT)! 

I am currently attempting to utilise the [CLS] token embedding of the output of pretrained MusicBERT as a summary of MIDI music piece and to also make an [EncoderDecoder model](https://huggingface.co/docs/transformers/v4.20.1/en/model_doc/encoder-decoder#transformers.EncoderDecoderModel) for training on some sequence generation task.

First I executed the following to get compatible version of fairseq in Colab:

```
%cd /content/
!git clone https://github.com/pytorch/fairseq
%cd fairseq
!git checkout 336942734c85791a90baa373c212d27e7c722662   # provided checkpoints are trained with this version
!pip install --editable ./

#To run shellscripts in cells with !bash
import os
os.environ['PYTHONPATH'] += ":/content/fairseq/"
```

Eventually I was also unable to load the provided pretrained checkpoint `checkpoint_last_musicbert_small.pt` by simply using the following and get the same `Could not infer model type` error:

```
print('loading model and data')

roberta = RobertaModel.from_pretrained('.', 
  checkpoint_file = 'checkpoints/checkpoint_last_musicbert_small.pt')
```
![image](https://user-images.githubusercontent.com/42506819/177032932-f01a0ec3-6ad1-41e9-9611-774f7cc44b5c.png)

Could you please tell me the simplest way to load the pretrained checkpoint as a fairseq RoBERTa model with/without using the shellscripts for finetuning on downstream tasks in the `musicbert` folder? 

Thank you in advance! :D

**Comment by mlzeng** [comment]
Hi @tripathiarpan20

The architecture of the MusicBERT model is slightly different from the original RoBERTa model since MusicBERT will process octuple tokens. The MusicBERT model (encoder) has a similar input/output format as the original RoBERTa model with only one restriction: the length of the sequence of tokens should be a multiple of 8. So I think the pre-trained model can fit into your use case.

You must load the pre-trained MusicBERT model using the `user_dir` keyword to activate the MusicBERT plugin.

You can refer to `musicbert/eval_genre.py`:
```python
roberta = RobertaModel.from_pretrained(
    '.',
    checkpoint_file=sys.argv[1],
    data_name_or_path=sys.argv[2],
    user_dir='musicbert'    # activate the MusicBERT plugin with this keyword
)
```

**Comment by tripathiarpan20** [comment]
Thanks for the response! :)
I see, that's really convenient.

I took a look through the same but was confused by the errors, the current doubts I have are:
> What should be the current directory while executing the snippet?
> Do we need the `data_name_or_path` keyword if we only plan to load the pretrained model?

Basically the same error persists with addition of `user_dir='musicbert'` with the current directory as `muzic/musicbert`, as seen in this snippet below:

![image](https://user-images.githubusercontent.com/42506819/177035041-b368dfc5-09fd-4d51-83eb-537d4690fc21.png)

**Comment by mlzeng** [comment]
The expected current directory is `muzic/musicbert`.
The plugin is located in `muzic/musicbert/musicbert` so the keyword `user_dir` is expected to be `musicbert`.

**Comment by tripathiarpan20** [comment]
Then the model should load properly as the current directory was set to `muzic/musicbert` as seen with output of `%pwd` in last reply, however it is not working :sweat:

**Comment by mlzeng** [comment]
It seems that there are some compatibility problems in the released checkpoints. You may try to follow the steps in https://github.com/microsoft/muzic/issues/51#issuecomment-1115821739 to produce a working checkpoint.

**Comment by mlzeng** [comment]
I will reproduce the experiment again on the exact same fairseq version to get compatible checkpoints.

**Comment by tripathiarpan20** [comment]
Thank you.

I attempted to do so earlier without a dataset, this time I shall try following the steps in the `musicbert/README.md`, can you confirm whether [this](https://fairseq.readthedocs.io/en/v0.10.2/command_line_tools.html#fairseq-train) is the appropriate documentation for fairseq-train compatible with `musicbert` implementation here?  

Also, would following [#51 (comment)](https://github.com/microsoft/muzic/issues/51#issuecomment-1115821739) yield the same but working pretrained checkpoint? i.e, not at all finetuned on genre prediction?

**Comment by mlzeng** [comment]
All command-line tools will work for the MusicBERT model just like the RoBERTa model. (don't forget the `--user-dir` option)
You can set the learning rate to zero so the parameters inside the model won't change.

**Comment by tripathiarpan20** [comment]
With your directions and referring to `musicbert/README.md` I was able to replicate the pretrained model (but along with genre classification head) that can be loaded by fairseq `RobertaModel.from_pretrained`, it can be seen in the section `Attempting to create working checkpoint` in this [notebook](https://colab.research.google.com/drive/1cCJr9s37P_w3ZHa-KPjH2cFVGXSVTTt_?usp=sharing). 

Setting `--lr 0` lead to passing of the assertions that common parts of architectures have same weight, i.e, no change in model weights from provided pretrained weights in `musicbert/README.md`: 

![image](https://user-images.githubusercontent.com/42506819/177040915-98428a59-8d30-448f-a8d3-2d4ed6250584.png)
![image](https://user-images.githubusercontent.com/42506819/177041078-70c917f0-1a3f-4ab1-bdc9-ad2366a2f911.png)
![image](https://user-images.githubusercontent.com/42506819/177040934-a7d1debb-5f6f-414b-924a-f5b958a6107b.png)

The rest of the checkpoint values (except `cfg` and `args`) were copied:
![image](https://user-images.githubusercontent.com/42506819/177041024-cab0abc4-82e2-45b7-909d-52fdc75f3549.png) 

The saved checkpoints can be loaded directly now (given fairseq is installed with reference to [comment](https://github.com/microsoft/muzic/issues/51#issuecomment-1173043024) above):
![image](https://user-images.githubusercontent.com/42506819/177041189-a42a2a73-d619-4cd1-a2dc-cbf321c1942b.png)
![image](https://user-images.githubusercontent.com/42506819/177041311-a6b7c2e5-5e4e-4e15-b698-0cfce7bbbae2.png)


Drive links to saved checkpoints:
- [checkpoint_last_musicbert_small_w_genre_head.pt](https://drive.google.com/file/d/1-BW45Vu80GU86ejTT4PFkgjvDhhYWatS/view?usp=sharing) (22.8 mil params)
- [checkpoint_last_musicbert_base_w_genre_head.pt](https://drive.google.com/file/d/1-6GJyolMS-z-WHdrwzmZGzzeTc01CldF/view?usp=sharing) (103.9 mil params)
