### ISSUE TITLE
How to generate dict file needed for songmass?

### ISSUE THREAD

**Issue by hf-xz** [microsoft/muzic#55]
songmasss中提供的`dict.lyric.txt`和`dict.melody.txt`是基于作者给出的训练集的英文字典，如何通过我们自己的数据库获得中文字典呢？

**Comment by hfxuanzai** [comment]
作者[@Kaitao Song](https://outlook.live.com/mail/0/deeplink?mailtouri=mailto%3Akaitaosong%40microsoft.com)的邮件回答内容如下：
>Hi, dict generation is same as fairseq, just like https://github.com/facebookresearch/fairseq/blob/main/fairseq_cli/preprocess.py. An example is like https://github.com/facebookresearch/fairseq/tree/main/examples/translation#iwslt14-german-to-english-transformer. BTW, you can also tokenize your data by yourself, and the dictionary format of fairseq is as:
“word1 frequency1
 word2 frequency2
…
”
