### ISSUE TITLE
[MusicBERT] Conflicts in tokenizing OctupleMIDI string to indices

### ISSUE THREAD

**Issue by tripathiarpan20** [microsoft/muzic#59]
Hi!

With reference to [`musicbert/eval_genre.py`]() and [fairseq examples](https://github.com/facebookresearch/fairseq/blob/main/examples/roberta/README.md#apply-byte-pair-encoding-bpe-to-input-text), it was found that there are two ways to tokenize and OctupleMIDI string into indices:
- By using `label_dict = RobertaModel.task.label_dictionary` as hinted in `musicbert/eval_genre.py`
- By using `RobertaModel.encode` as hinted in [fairseq examples](https://github.com/facebookresearch/fairseq/blob/main/examples/roberta/README.md#apply-byte-pair-encoding-bpe-to-input-text) 

![image](https://user-images.githubusercontent.com/42506819/177047804-77402ebf-0ce6-4f49-8e6e-1aa818875750.png)

However, the `RobertaModel.encode` seems to be totally disfunctional considering that it should work like the snips below: 

![image](https://user-images.githubusercontent.com/42506819/177048047-dcacbddb-f96e-4144-ad2a-d15e74c02041.png)
![image](https://user-images.githubusercontent.com/42506819/177048022-cc34d2b2-d5f2-46f5-bb29-6e1611b42e39.png)

Can you confirm what is the correct way to encode an OctupleMIDI string to token indices to feed forward to MusicBERT (RobertaModel)?

**Comment by tripathiarpan20** [comment]
Another confusion I have is that how do we decode of Token indices back to OctupleMIDI string (which could be encoded back to `miditoolkit.midi.parser.Midifile` using preprocess.encoding_to_MIDI(preprocess.str_to_encoding(*OctupleMIDI string*)) )?

The `RobertaModel.task.label_dictionary` does not seem to have any `decode` function, and it seems that `RobertaModel.decode()` would give random output too.

**Comment by mlzeng** [comment]
The `RobertaModel.encode` and `RobertaModel.decode` methods use BPE which is used for NLP, so it won't recognize MusicBERT tokens. It's better to encode and decode with the dictionary directly.

**Comment by tripathiarpan20** [comment]
After reading `musicbert/musicbert/__init__` & [fairseq roberta model](https://github.com/facebookresearch/fairseq/blob/336942734c85791a90baa373c212d27e7c722662/fairseq/models/roberta/model.py#L391), things are a bit clearer too, thanks!
