### ISSUE TITLE
[MusicBERT] Evaluation bug

### ISSUE THREAD

**Issue by SkyAndCloud** [microsoft/muzic#66]
Hi, I tried to evaluate NSP tasks by `python -u eval_nsp.py checkpoints/checkpoint_last_nsp_next_checkpoint_last_musicbert_small.pt next_data_bin` but encountered the following errors:
```
loading model and data
disable_cp = False
mask_strategy = ['bar']
convert_encoding = OCTMIDI
crop_length = None
Request for https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json timed-out (attempt 0). Retrying with a timeout of 10 secs
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/python3/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```
It seems that `RobertaModel.from_pretrained` tried to download some files? Can I download these files manually and then put them at the corresponding directory to make all things done?

**Comment by mlzeng** [comment]
Hi @SkyAndCloud 

The file is a BPE dictionary for NLP. It's used by the original RoBERTa but not used by MusicBERT. You can download it manually and then put them in the corresponding directory to make all things done.
