### ISSUE TITLE
【teleMelody】

### ISSUE THREAD

**Issue by punkcure** [microsoft/muzic#72]
I tried lyrics2beat checkpoints and found that the beat pattern inferred from model include repeated data,  such as 
![image](https://user-images.githubusercontent.com/7077441/184840362-9a29ef07-702c-431a-8974-454750c1f57b.png)
for example,[2,3,3,0,0], does that mean the note 1 and note 2 share beat 3 ? or the result is a bad case?

**Comment by jzq2000** [comment]
Yes.   In TeleMelody, duration of a note can range from a 1/16 note to a whole note, while a beat is a 1/4 note.  In such a setting,  two notes may share a beat (e.g., two 1/8 notes).

**Comment by punkcure** [comment]
I got it, thanks
