### ISSUE TITLE
Code of Museformer

### ISSUE THREAD

**Issue by shiyanpei** [microsoft/muzic#79]
Hi

   Muzic is a fantastic project, I always keep following your works. 

   May I ask that the code of Museformer? As from your paper :Museformer: Transformer with Fine- and
Coarse-Grained Attention for Music Generation, you said that the source code can be found in this github page.

   Thank you!

**Comment by tripathiarpan20** [comment]
I have the same thoughts as @shiyanpei about Muzic as an amazing open-source project and wondering about the availability of code and pretrained checkpoints of Museformer.
Thanks.

@tan-xu @mlzeng

**Comment by btyu** [comment]
Hi

The code now has been uploaded. Thank you for your interest!

@shiyanpei @tripathiarpan20

**Comment by btyu** [comment]
Since there is no update on this issue, we close it now. Please feel free to reopen it if necessary.
