### ISSUE TITLE
[teleMelody] How does lyric and chord corresponds with each other?

### ISSUE THREAD

**Issue by elricwan** [microsoft/muzic#82]
Hi there, from the test example, how does the lyric and chord corresponds with each other? I thought every [sep] represents one chord, but apparently the number does not match. If we match every word to one chord, then number does not match either. Here is example:
en:
```
this thing called love and i just [sep] han -dle it [sep] this thing called love and i must get [sep] round to it [sep] i rea -dy [sep]
```
```
Eb:maj7 Eb:maj7 C:dim C:dim C:dim C:dim C:dim C:dim
```
ch:
```
斑 驳 的 夜 色 在 说 什 么 [sep] 谁 能 告 诉 我 如 何 选 择 [sep] 每 当 我 想 起 分 离 时 刻 [sep] 悲 伤 就 逆 流 成 河 [sep] 你 给 的 温 暖 属 于 谁 呢 [sep] 谁 又 会 在 乎 我 是 谁 呢 [sep] 每 当 我 想 起 你 的 选 择 [sep] 悲 伤 就 逆 流 成 河 [sep] 失 去 了 你 也 是 种 获 得 [sep] 一 个 人 孤 单 未 尝 不 可 [sep] 每 当 我 深 夜 辗 转 反 侧 [sep] 悲 伤 就 逆 流 成 河 [sep] 离 开 你 也 是 一 种 快 乐 [sep] 没 人 说 一 定 非 爱 不 可 [sep] 想 问 你 双 手 是 否 温 热 [sep] 悲 伤 就 逆 流 成 河 [sep] 我 想 是 因 为 我 太 天 真 [sep] 难 过 是 因 为 我 太 认 真 [sep] 每 当 我 想 起 你 的 眼 神 [sep] 悲 伤 就 逆 流 成 河 [sep]
```

```
C:m7 C:m7 G:m7 Bb: C:m7 F:m7 C:m7 C:m7 G:m7 Bb: C:m7 F:m7 C:m C:m G:m7 F:m7 C:m7 F:m7 C:m C:m G:m7 C:m7 C:m7 F:m7 C:m7 C:m7 G:m7 G:m7 C:m F:m7 C:m7
```

**Comment by jzq2000** [comment]
It is inferred from ground truth melody, and every bar represents one chord.

**Comment by elricwan** [comment]
Thank you for the quick response, but I am still a little bit confused. During the inference stage, we need to input both the lyric and chord, is there any rule I need to follow? For instance:
If my lyric looks like:

```
斑 驳 的 夜 色 在 说 什 么 [sep] 谁 能 告 诉 我 如 何 选 择 [sep] 每 当 我 想 起 分 离 时 刻 [sep] 悲 伤 就 逆 流 成 河 [sep]
```

It contains four subsection, 34 words in total. Then, how many chords should I input? Is there a recommend range? Thank you!

**Comment by jzq2000** [comment]
You should input the same number of chords to match the number of bars (which can be calculated from inferred rhythmic patterns).

**Comment by elricwan** [comment]
I see, thank you!
