### ISSUE TITLE
请问当midi文件包含小节特别多的时候该怎么处理

### ISSUE THREAD

**Issue by BinLiang2021** [microsoft/muzic#90]
手上有一个 有1w个小节左右的midi文件
想利用这个仓库里的 ROC/gen.py 处理成 notes，trend 文件。
但是因为太长了，pool这个库会报错。请问该如何处理啊

**Comment by CatherineJun** [comment]
请问你使用gen.py处理数据时，会出现“ (0.00%) midi files successfully processed”的情况吗？

**Comment by CatherineJun** [comment]
请问data/lmd_processed/valid文件在哪里呀

**Comment by BinLiang2021** [comment]
> 请问data/lmd_processed/valid文件在哪里呀

哈咯。你之前问的那个问题，是的，会出现 success 0/0，那个现象。需要修改两个文件的参数，一个 是 gen.py 一个是 magenta_chord_recognition.py 就能处理了。你后来这个 valid 文件 是你要自己设置吧？我也不清楚你具体问的什么，你可以再开一个 issue 问问开发者？
