### ISSUE TITLE
[Museformer] Could not override 'task.dataset_impl'

### ISSUE THREAD

**Issue by artyomche9** [microsoft/muzic#91]
Hello, I, following the instructions in the README.md, create a virtual environment in Linux on WSL 2, download the checkpoint model, run the command that runs tgen/generation__mf-lmd6remi-x.sh and get the error 
hydra.errors.ConfigCompositionException: Could not override 'task.dataset_impl'.
To append to your config use +task.dataset_impl=null

I'm running the model on a 3080 Ti

**Comment by btyu** [comment]
Hi! This problem didn't appear when I test it. I guess it is related to the environment. Could you please recheck the versions of the packages and offer me more details, or try this docker image: ``registry.cn-shanghai.aliyuncs.com/taons/museformer:v1.0``? 

Thx.

**Comment by ZZDoog** [comment]
I have the same problem as yours, try to install the same versions of fairseq as README.md.
After I change the fairseq 0.12.2 to 0.10.2 as README, the error disappear.
I hope this helps you

**Comment by ZZDoog** [comment]
> Hi! This problem didn't appear when I test it. I guess it is related to the environment. Could you please recheck the versions of the packages and offer me more details, or try this docker image: `registry.cn-shanghai.aliyuncs.com/taons/museformer:v1.0`?
> 
> Thx.

I try to pull this docker image, it seems to closes, can you upload it again?
Thx.

**Comment by btyu** [comment]
> > Hi! This problem didn't appear when I test it. I guess it is related to the environment. Could you please recheck the versions of the packages and offer me more details, or try this docker image: `registry.cn-shanghai.aliyuncs.com/taons/museformer:v1.0`?
> > Thx.
> 
> I try to pull this docker image, it seems to closes, can you upload it again? Thx.

It seems still working. What did it say? Or, you may try again.

**Comment by btyu** [comment]
Since there is no update, I am closing this issue. Feel free to reopen it if needed.

**Comment by aletote** [comment]
I got the same error as the OP, what's the solution please?
